############## Log properties ###############
logging:
  level:
    org.springframework.security: DEBUG
    com.woowrale.architecture.eurekadiscovery: DEBUG
############## Server properties ###############
server:
  port: 8790
  tomcat:
    basedir: server/tomcat/
############## Cloud properties ###############
spring:
  application:
    name: keurekaservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8790/
    register-with-eureka: false
    fetch-registry: false